# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/singleadapter
    docker:
      - image: circleci/android:api-27
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "singleadapter/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "singleadapter/build.gradle" }}
      - run:
          name: Run SingleAdapter Module
          command: ./gradlew :singleadapter:test
      - store_artifacts:
          path: singleadapter/build/reports
      - store_test_results:
          path: singleadapter/build/test-results
      - run:
          name: Run App
          command: ./gradlew :app:test
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - store_artifacts:
          path: singleadapter/build/reports